services:
  app:
    container_name: app-container
    build:
      context: .
      target: dev-live-reload
    ports:
      - "50051:50051"
      - "6060:6060"   # pprof用ポートを追加
    environment:
      APP_ENV: development
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: mysql
      DATABASE_NAME: mission_sample
      REDIS_ADDRESS: redis:6379
      PRIVATE_KEY_PATH: ./server/config/secret.key
    volumes:
      - .:/app
      - go_mod:/go/pkg/mod
      - go_build:/root/.cache/go-build

volumes:
  go_mod:
  go_build: