// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.2
// source: verification.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_none     State = 0 // Initialize Verificationに移行
	State_active   State = 1 // Verification中
	State_pause    State = 2 // Bidirectionalの一時停止
	State_quit     State = 3 // Bidirectionalの強制終了
	State_next     State = 4 // Bidirectionalを終了し、次のVerificationを待つ
	State_finish   State = 5 // BidirectionalとServerStreamの終了。検証自体の終了
	State_quit_all State = 6 // BidirectionalとServerStreamの強制終了。検証自体の終了
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "none",
		1: "active",
		2: "pause",
		3: "quit",
		4: "next",
		5: "finish",
		6: "quit_all",
	}
	State_value = map[string]int32{
		"none":     0,
		"active":   1,
		"pause":    2,
		"quit":     3,
		"next":     4,
		"finish":   5,
		"quit_all": 6,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_verification_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_verification_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{0}
}

type VerificationStateServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VerificationStateServerRequest) Reset() {
	*x = VerificationStateServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationStateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationStateServerRequest) ProtoMessage() {}

func (x *VerificationStateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationStateServerRequest.ProtoReflect.Descriptor instead.
func (*VerificationStateServerRequest) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{0}
}

type VerificationStateServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerificationId int64 `protobuf:"varint,1,opt,name=verification_id,json=verificationId,proto3" json:"verification_id,omitempty"`
	State          State `protobuf:"varint,2,opt,name=state,proto3,enum=centray.State" json:"state,omitempty"`
	ByteCount      int32 `protobuf:"varint,3,opt,name=byte_count,json=byteCount,proto3" json:"byte_count,omitempty"`
	RequestPerSec  int32 `protobuf:"varint,4,opt,name=request_per_sec,json=requestPerSec,proto3" json:"request_per_sec,omitempty"`
	ExecThreshold  int32 `protobuf:"varint,5,opt,name=exec_threshold,json=execThreshold,proto3" json:"exec_threshold,omitempty"`
}

func (x *VerificationStateServerResponse) Reset() {
	*x = VerificationStateServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationStateServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationStateServerResponse) ProtoMessage() {}

func (x *VerificationStateServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationStateServerResponse.ProtoReflect.Descriptor instead.
func (*VerificationStateServerResponse) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{1}
}

func (x *VerificationStateServerResponse) GetVerificationId() int64 {
	if x != nil {
		return x.VerificationId
	}
	return 0
}

func (x *VerificationStateServerResponse) GetState() State {
	if x != nil {
		return x.State
	}
	return State_none
}

func (x *VerificationStateServerResponse) GetByteCount() int32 {
	if x != nil {
		return x.ByteCount
	}
	return 0
}

func (x *VerificationStateServerResponse) GetRequestPerSec() int32 {
	if x != nil {
		return x.RequestPerSec
	}
	return 0
}

func (x *VerificationStateServerResponse) GetExecThreshold() int32 {
	if x != nil {
		return x.ExecThreshold
	}
	return 0
}

type VerificationDataBidirectionalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerificationId int64  `protobuf:"varint,1,opt,name=verification_id,json=verificationId,proto3" json:"verification_id,omitempty"`
	Data           []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *VerificationDataBidirectionalRequest) Reset() {
	*x = VerificationDataBidirectionalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationDataBidirectionalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationDataBidirectionalRequest) ProtoMessage() {}

func (x *VerificationDataBidirectionalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationDataBidirectionalRequest.ProtoReflect.Descriptor instead.
func (*VerificationDataBidirectionalRequest) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{2}
}

func (x *VerificationDataBidirectionalRequest) GetVerificationId() int64 {
	if x != nil {
		return x.VerificationId
	}
	return 0
}

func (x *VerificationDataBidirectionalRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type VerificationDataBidirectionalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerificationId int64  `protobuf:"varint,1,opt,name=verification_id,json=verificationId,proto3" json:"verification_id,omitempty"`
	Data           []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *VerificationDataBidirectionalResponse) Reset() {
	*x = VerificationDataBidirectionalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationDataBidirectionalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationDataBidirectionalResponse) ProtoMessage() {}

func (x *VerificationDataBidirectionalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationDataBidirectionalResponse.ProtoReflect.Descriptor instead.
func (*VerificationDataBidirectionalResponse) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{3}
}

func (x *VerificationDataBidirectionalResponse) GetVerificationId() int64 {
	if x != nil {
		return x.VerificationId
	}
	return 0
}

func (x *VerificationDataBidirectionalResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChangeStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerificationId int64 `protobuf:"varint,1,opt,name=verification_id,json=verificationId,proto3" json:"verification_id,omitempty"`
	State          State `protobuf:"varint,2,opt,name=state,proto3,enum=centray.State" json:"state,omitempty"`
}

func (x *ChangeStateRequest) Reset() {
	*x = ChangeStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStateRequest) ProtoMessage() {}

func (x *ChangeStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStateRequest.ProtoReflect.Descriptor instead.
func (*ChangeStateRequest) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeStateRequest) GetVerificationId() int64 {
	if x != nil {
		return x.VerificationId
	}
	return 0
}

func (x *ChangeStateRequest) GetState() State {
	if x != nil {
		return x.State
	}
	return State_none
}

type ChangeStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeStateResponse) Reset() {
	*x = ChangeStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStateResponse) ProtoMessage() {}

func (x *ChangeStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verification_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStateResponse.ProtoReflect.Descriptor instead.
func (*ChangeStateResponse) Descriptor() ([]byte, []int) {
	return file_verification_proto_rawDescGZIP(), []int{5}
}

var File_verification_proto protoreflect.FileDescriptor

var file_verification_proto_rawDesc = []byte{
	0x0a, 0x12, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x79, 0x22, 0x20, 0x0a,
	0x1e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0xde, 0x01, 0x0a, 0x1f, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x63, 0x65,
	0x6e, 0x74, 0x72, 0x61, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x62, 0x79, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x65, 0x72,
	0x5f, 0x73, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x78, 0x65,
	0x63, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x65, 0x78, 0x65, 0x63, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64,
	0x22, 0x63, 0x0a, 0x24, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x64, 0x0a, 0x25, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27,
	0x0a, 0x0f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x63, 0x0a, 0x12, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x27, 0x0a, 0x0f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x63, 0x65, 0x6e, 0x74,
	0x72, 0x61, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x22, 0x15, 0x0a, 0x13, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x56, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x08, 0x0a, 0x04, 0x6e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x70, 0x61, 0x75, 0x73, 0x65, 0x10,
	0x02, 0x12, 0x08, 0x0a, 0x04, 0x71, 0x75, 0x69, 0x74, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x6e,
	0x65, 0x78, 0x74, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x10,
	0x05, 0x12, 0x0c, 0x0a, 0x08, 0x71, 0x75, 0x69, 0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x10, 0x06, 0x42,
	0x0a, 0x5a, 0x08, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_verification_proto_rawDescOnce sync.Once
	file_verification_proto_rawDescData = file_verification_proto_rawDesc
)

func file_verification_proto_rawDescGZIP() []byte {
	file_verification_proto_rawDescOnce.Do(func() {
		file_verification_proto_rawDescData = protoimpl.X.CompressGZIP(file_verification_proto_rawDescData)
	})
	return file_verification_proto_rawDescData
}

var file_verification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_verification_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_verification_proto_goTypes = []interface{}{
	(State)(0),                                    // 0: centray.State
	(*VerificationStateServerRequest)(nil),        // 1: centray.VerificationStateServerRequest
	(*VerificationStateServerResponse)(nil),       // 2: centray.VerificationStateServerResponse
	(*VerificationDataBidirectionalRequest)(nil),  // 3: centray.VerificationDataBidirectionalRequest
	(*VerificationDataBidirectionalResponse)(nil), // 4: centray.VerificationDataBidirectionalResponse
	(*ChangeStateRequest)(nil),                    // 5: centray.ChangeStateRequest
	(*ChangeStateResponse)(nil),                   // 6: centray.ChangeStateResponse
}
var file_verification_proto_depIdxs = []int32{
	0, // 0: centray.VerificationStateServerResponse.state:type_name -> centray.State
	0, // 1: centray.ChangeStateRequest.state:type_name -> centray.State
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_verification_proto_init() }
func file_verification_proto_init() {
	if File_verification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_verification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationStateServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationStateServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationDataBidirectionalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationDataBidirectionalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_verification_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_verification_proto_goTypes,
		DependencyIndexes: file_verification_proto_depIdxs,
		EnumInfos:         file_verification_proto_enumTypes,
		MessageInfos:      file_verification_proto_msgTypes,
	}.Build()
	File_verification_proto = out.File
	file_verification_proto_rawDesc = nil
	file_verification_proto_goTypes = nil
	file_verification_proto_depIdxs = nil
}
